workflows:
android-debug:
name: Android Debug APK
enviroment:
vars:
PACKAGE_NAME: "com.bropunzellsoftware.bastetsavanna"
scripts:
- name: Build Debug APK
script: |
./gradlew assembleDebug

artifacts:
- app/build/outputs/apk/debug/*.apk

